export const SITE_NAV_LINKS = [
  { label: "Home", path: "/" },
  { label: "Competitions", path: "/competitions/" },
  { label: "Upcoming Fixtures", path: "/fixtures/" },
  { label: "World Cup 2026", path: "/worldcup2026/" },
  { label: "Season Previews (BETA)", path: "/seasonpreviews/" },
  { label: "BTTS Teams", path: "/bttsteams/" },
  { label: "BTTS No Teams", path: "/btts-no-teams/" },
  { label: "BTTS Games", path: "/bttsfixtures/" },
  { label: "Over 2.5 Goals Games", path: "/fixtureshigh/" },
  { label: "Highest Scoring Leagues", path: "/highest-scoring-leagues/" },
  { label: "Over 2.5 Teams", path: "/o25/" },
  { label: "Lowest Scoring Leagues", path: "/u25/" },
  { label: "About", path: "/about/" },
  { label: "Methodology", path: "/methodology/" },
  { label: "FAQ", path: "/faq/" },
];
